### ISSUE TITLE
Some Questions About TacTok

### ISSUE THREAD

**Issue by zhaoyu-li** [LASER-UMASS/TacTok#1]
Hi, I run CoqGym and your model but find some questions:

1. `TacTok/extract_proof_steps.py` doesn't provide the field "prev_tokens", so the proof steps data doesn't have this field. But in `TacTok/dataloader.py`,  the function `create_dataloader` has the field `prev_tokens`. Could you mind tell me how to have this field and train the model?
2.  Could you please tell me if you train the model using synthetic data or not? In `main.py --datapath proof_steps/human`, it seems like you also train on synthetic data.
3.  It seems like there is a file called `token_vocab.pickle`, could you please provide this file?

Thank you for your time!

**Comment by efirst** [comment]
1. I have added the processing script and updated the directions in the `README`. After running `TacTok/extract_proof_steps.py`, you should run `TacTok/process_proof_steps.py`, which will generate new proof steps with the `prev_tokens` field in `TacTok/processed/proof_steps`. Alternatively, the `processed.tar.gz` file from the replication package link can be downloaded and has the already processed proof steps with the `prev_tokens` field.
2. We do not train the model using synthetic data. I have corrected the default `--datapath` in `options.py` to be what we use, which is `processed/proof_steps`.
3. I have added this file,`TacTok/token_vocab.pickle`.
