### ISSUE TITLE
A small Question About TacTok

### ISSUE THREAD

**Issue by zhaoyu-li** [LASER-UMASS/TacTok#2]
Hi, for Tac model, you provide two files: `tac_vocab.pickle` and `tac_vocab_no_unk.pickle`, would you please tell me which one is the file you used? For the pre-trained model, I find that the first dimension of tactic_embedding is 49. And the size of `tac_vocab_no_unk.pickle` is 49 while the size of `tac_vocab.pickle` is 50, is that means you use `tac_vocab_no_unk.pickle`? 

However, when I run your model on the `demos` dataset, it seem like the performance you report in the paper use ` tac_vocab.pickle`. And when I run on other dataset, the model using` tac_vocab.pickle` may report an error since the size of its vocabulary is 50. 

Can you please help me solve this issue? Thanks.

**Comment by efirst** [comment]
For the Tac model, we use `tac_vocab_no_unk.pickle` with vocab size 49.
